import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VolleyScore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} dark:bg-[#15202b] bg-white`}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
